version: '3.9'

services:
  api1:
    container_name: api1
    build: .
    hostname: api1
    environment:
      - DATABASE_URL=database
      - PORT=3000
    depends_on:
      - db-postgres
      #- cache
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '400MB'
    networks:
      - host
  api2:
    container_name: api2
    build: .
    hostname: api2
    environment:
      - DATABASE_URL=database
      - PORT=3001
    depends_on:
      - db-postgres
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '400MB'
    networks:
      - host
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - host
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '200MB'
  db-postgres:
    image: postgres
    container_name: postgres_rinha
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    hostname: database
    environment:
      POSTGRES_DB: rinha_db
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '500MB'
    networks:
      - host
networks:
  host: